name: Deploy fib-k8s
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: $(git rev-parse HEAD)
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - uses: actions/checkout@v2
      - run: openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
      - run: curl https://sdk.cloud.google.com | bash > /dev/null;
      - run: source $HOME/google-cloud-sdk/path.bash.inc
      - run: gcloud components update kubectl
      - run: gcloud auth activate-service-account --key-file service-account.json
      - run: gcloud config set project fib-k8s-333906
      - run: gcloud config set compute/zone us-central1-c
      - run: gcloud container clusters get-credentials fib-k8s
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t montecb/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true USERNAME/react-test npm test
      - run: bash ./deploy.sh
          